// these colors will bbe used for the background of the book and the stripes
// so make sure any combination of two colors looks good
var colors = ['#325453', '#517174', '#E5D58', '#DCBE87', '#AD6A34', '#4E1D04'];

// you can adjust these, and keep in mind some might go over the Max if
// the height would've been higher than the screen
var widthMin = 70;
var widthMax = 100;

// I will start the episode number at 175
var num = 175;

// Make sure that these correlate exactly. title[0] is the first episode
// and height[0] is also the first episode
var titles = ["Beautiful Library Renovations",
    "Libraries as Inspirational Space",
    "Open Access and its Enemies",
    "Handling New Media",
    "A Helluva Engineer",
    "Patents & Trolls",
    "The Road To Litigation",
    "Collecting the Now",
    "Life's Not Fair But It Can Be Fair-Use",
    "Google Books & Libraries",
    "What Does Google Really Want?",
    "Metadata is Important!",
    "Metadata's Evil Twin",
    "The NSA Show",
    "What Are You Reading?",
    "Expunge our Digital History",
    "FOIA",
    "Military Libraries II: Into The Archives",
    "Back To Bad Luck And Trouble In Libraries",
    "First-person Shelver",
    "There's No Archive Like Show Archives",
    "The Rock and Roll Hall of Fame Library and Archives",
    "Citizen Archiving",
    "The Tapes Dreams Are Made Of",
    "Technoarchaeology and the DEEP PAST",
    "The Sonification of Space Data",
    "Problem Based Learning",
    "The Decatur Book Festival",
    "Labor Archives",
    "Citizen Archiving II: Documents & Dischord",
    "Raw Data is an Oxymoron",
    "Software as a Subject",
    "The DLF Show",
    "The DLF Fine Fellows Show",
    "The DLF Forum Recap Show",
    "The GSU Case",
    "The Library Beyond The Book",
    "Professional Development",
    "Posters",
    "WikiDoes, WikiDon't",
    "A LITSmas Carol",
    "The Library of/at Alexandria",
    "The Barbie Re-Mix",
    "The Gendered Archive",
    "A Good Archive Is Hard To Find",
    "Gender Studies and the Librarian",
    "Fake Library Statistics",
    "Love in the Archives",
    "Viral Library Videos",
    "How's The DPLA Doing?",
    "How's The DPLA Working?",
    "How's the DPLA Looking?",
    "Walking Dead Air",
    "Leaky Records and FERPA Derp",
    "The People's Platform",
    "SpotiFIGHT!",
    "Help Murmur Out!",
    "Information Doesn't Want to be Free",
    "Community Builder, Corporate Resistor",
    "The Internet of Things",
    "In the Library!",
    "In the Library Too!",
    "Archives Die Unless We Talk About Them",
    "Avoiding Dead Air",
    "The DC Punk Archive",
    "Beach Libraries",
    "Our Little Free Library",
    "Once a Librarian, Always a Librarian",
    "SpotiFIGHT! II: In the Ring",
    "The Atlanta Zine Library II: The Paper-and-Staple Boogaloo",
    "Authors: Dave Eggers",
    "Authors: Flannery O'Connor",
    "Authors: Stephen Jay Gould",
    "Authors: P. G. Wodehouse",
    "Hey",
    "Authors: Lucille Clifton",
    "Library Unicorn Job",
    "Open Sourcing America's Operating System",
    "Respect des Fonds, Respect des Planet",
    "Library 20/20",
    "Sustainability in Libraries",
    "High Density Storage Facilities",
    "In the Jailhouse Now",
    "Archive All the Data!",
    "The Library Freedom Project",
    "Library 20/20 Episode 1",
    "The Story of the Stuff",
    "Let's Get Phygital",
    "Spoti-FIGHT! Part III: Return of the Revenge of the Independent Artist",
    "In Instagram We Trust",
    "The 404",
    "From the Desk of the Chief Technology Strategist",
    "Our Predictions for the New Year",
    "Google Books and Libraries Part II",
    "The Museum Experience",
    "Music Archives I",
    "Music Archives II: Hip Hop",
    "Music Archives III: All That Jazz",
    "Georgia Blood and Southern Love teaser",
    "Music Archives IV: DJ Screw",
    "Music Archives V: Indie Preserves",
    "Citizen Archiving III: The Master Tapes",
    "Unpacking Manuel's Tavern",
    "The Murakami Shenanigans",
    "Archive the Future II: Documenting the Now",
    "Telling Our Story",
    "Bert Lyons and Exactly",
    "Facebook is not Your Archive",
    "150 Themes",
    "Another 150 Themes",
    "Earth Day: Sustainability Roundtable",
    "Pirates on the Seas of Scholarship",
    "The Unbearable Lightness of Streaming",
    "As Your Attorney, I Advise You to Drive at Top Speed",
    "The Myth of the Archive",
    "Bonus Content: It's a Beautiful Game",
    "The Voyager Record",
    "Beach Libraries",
    "On the Rove",
    "Giving All the Birds a Chance",
    "Reimagining the Oldest Library in the World",
    "The Library Freedom Project",
    "Data Librarianship: Naked and Afraid",
    "Statistical Significance",
    "Data as Wood",
    "Data Driven Decisions",
    "Data as Packet-Switching Glitch Art",
    "The Unbearable Lightness of Streaming",
    "Question My Authority",
    "The Bad-ass Librarians of Timbuktu",
    "<accessrestrict>",
    "Talking to Each Other About Technology",
    "Tactical Urbanism and Mobile Libraries",
    "Radical Reference",
    "The NSA Show",
    "EveryLibrary II: Four Year Check-in",
    "Bonus Content: No Advertising",
    "Chaotic Neutral",
    "Serendipity and the Digital",
    "Literary Lacerations",
    "Question My Authority II: Peer Review",
    "Our Information Will Replace Us",
    "Taking a Critical Look",
    "Ancient Libraries",
    "Predictive Engineering",
    "Global Web Preservation",
    "The Olympic Studies Library",
    "A LITSmas Carol",
    "The LITSmas Holiday Special 2015",
    "Our Predictions for the New Year",
    "Weather Closing Announcement",
    "Dystopian Fiction",
    "What's the Future?",
    "Fake News",
    "This is What Democracy Sounds Like",
    "A Digital Dark Age",
    "Preserving Decision-Making Data",
    "Digital Resilience",
    "The Library Freedom Project",
    "The Liberated Archive",
    "Bibliometrics, Yay-hoo!",
    "Spoti-FIGHT! Part III: Return of the Revenge of the Independent Artist",
    "Copyright Hawks and Doves",
    "Full Interview with David Lowery",
    "You Better Run to the City of Data Refuge",
    "Smart Cities, Smart Libraries",
    "It's a Beautiful Game",
    "Town, Gown, Cardigan",
    "The Diversity Paradigm",
    "The Interplanetary File System",
    "Engineering the Hidden Library",
    "Metadata's Evil Twin",
    "Squaring the Circle",
    "The Freedome Library",
    "129,864,880",
    "The Human Library",
    "A Personal Guide To Open Access",
    "Doshi Drops the Mic",
    "Disrupting Mainstream History",
    "Trust But Verify",
    "More Publishing, More Problems",
    "Salute Your Jorts!",
    "Data as Wood",
    "97% Eclipse of the Heart",
    "Information Literacy for the Win!",
    "Dischord Records is History",
    "The DC Punk Archive",
    "Fossils... in Glorious 3D!",
    "The American Music Show",
    "Designing for Diversity",
    "Back to Bad Luck and Trouble",
    "Ready for Disaster!",
    "Happy Halloween From Lily Dale",
    "From Romance to Reality",
    "Whose Data? My Data!",
    "Data as Packet-Switching Glitch Art",
    "This I Believe",
    "The Mailbag",
    "The Material Oomph",
    "Homestar Runner, Gone in a Flash",
    "Citizen Archiving",
    "Citizen Archiving II: Documents &amp; Dischord",
    "LITSmas 2017",
    "Data Visualization",
    "The Snow Days",
    "Report From K-12",
    "Ask Me Who I Was",
    "Keep On Keeping On",
    "The Return of the Revenge of Analog",
    "A Good Leader is Hard to Find",
    "Professional Development",
    "Elvis Had Left The Library",
    "It Could Happen To You",
    "When the Past is the Present",
    "Outside the Framework",
    "The Bytegeist of Podcast Preservation",
    "Appetite for Instruction",
    "The Atlanta Black Archives Alliance",
    "The Library Beyond The Book",
    "Comprehensive and Totally Secure",
    "Open Access in the Global South",
    "What's New in the Public Domain?",
    "The People's Platform",
    "Here There Be Sea Dragons",
    "Washed Up Emo",
    "The Accidental Mentor",
    "The Southeast Data Librarian Symposium",
    "Archives Die Unless We Talk About Them",
    "The Great Speckled Bird",
    "The Common Good",
    "How to Read a Book",
    "Community Builder, Corporate Resistor",
    "Uncataloging Neutrality",
    "Bibliometrics, Yay-Hoo!",
    "For What It's Worth",
    "Our Information Will Replace Us",
    "Unpacking Manuel's Tavern",
    "Where Are We Going?",
    "Citizen Science in the Fossil Lab",
    "How To Read A Book II: Slow Reading",
    "The 404",
    "Academic Writing as Music",
    "Full Interview with Dave Beer for LITS 397",
    "OER: The Happening",
    "Our Catalogs, Ourselves",
    "TF is up with EU GDPR?!",
    "How To Write A Book: Engaging Design",
    "The Case For Comics",
    "Literature As Information",
    "The White Glove Show",
    "Community-Driven Archives",
    "Skynet Fail: AI in Libraries",
    "The Frontiers of Privacy",
    "LITSmas 2018",
    "What's New in the Public Domain?",
    "We Know Who We Are",
    "Man-Bats on the Media Landscape",
    "The (Library) Innovator's Dilemma",
    "Cruising the Library",
    "The Seminal Works Show",
    "Who Discovered the Archives?",
    "Fictional Libraries",
    "How To Write a Book II: Transformer",
    "Authors: Flannery O'Connor",
    "Teaching The Archives",
    "New Library, New Librarian",
    "Peer Review and the Cold War",
    "Plan S from Outer Space",
    "Whose Data? My Data!",
    "As Your Attorney I Advise You Again to Drive at Top Speed",
    "Deepfake",
    "Catastrophes of Literacy",
    "Libraries at Scale",
    "Full interview from LITS 422",
    "An Archive of Planet Earth",
    "The Voyager Record",
    "Resisting GAFAM",
    "How to Disappear Completely",
    "Presidential Libraries",
    "Raw Data is an Oxymoron",
    "The Library Between the Lines",
    "All Data Are Local",
    "Metadata in a Material World",
    "FlÃ¢neur",
    "Data Feminism",
    "Free Cut",
    "Data Cultures",
    "Authored by AI",
    "MARTA Archaeology",
    "Second Lives",
    "Bad Luck and Trouble: The Musician Edition",
    "Graffiti Kings",
    "Things New and Strange",
    "Material Data in a Material World",
    "The CASE Act",
    "Archivists Against History Repeating Itself",
    "Metadata of the Dead",
    "On Record: Tracing the Lifecycle of Political Archives",
    "Invest in Open",
    "Delete Yourself From Social Media",
    "How To Write A Book Chapter",
    "The Maintainers",
    "The Library Book",
    "LITSmas 2019, LITS Go To The Movies",
    "Mobilizing History with J. Mark Souther",
    "In the Year 2020",
    "When Did Efficiency Become the End Goal?",
    "The Rise of Populism and the Fall(?) of Open Access",
    "Ten Years, Man! TEN YEARS",
    "#DoNoHarm",
    "Libraries as Convivial Spaces",
    "Multimodal Information Literacy",
    "From Embedded To Rooted",
    "Open Access and its Enemies",
    "Open as a Process",
    "Artist in Residence",
    "Our Catalogs, Ourselves",
    "SpotiFIGHT!",
    "SpotiFIGHT! II: In the Ring",
    "Spoti-FIGHT! Part III: Return of the Revenge of the Independent Artist",
    "The American Music Show",
    "Homestar Runner, Gone in a Flash",
    "2020 AF",
    "The Interplanetary File System",
    "Open Syllabus",
    "An Archive of Planet Earth",
    "Data Murmuration",
    "Question My Authority",
    "GLAM-orizing Your Travel Plans",
    "Question My Authority II: Peer Review",
    "The Public Programming and Community Engagement Specialist",
    "Data Librarianship: Naked and Afraid",
    "Virtually Leading the Academic Library",
    "Statistical Significance",
    "Bodies on the Line",
    "Data Driven Decisions",
    "The Distant Reader, or: How to Read Lots and Lots and Lots of Books",
    "Nostalgia and Late Capitalism",
    "Doomscrolling",
    "The African American Struggle for Library Equality",
    "The Leiden Manifesto"];

var height = [3,
    2,
    25,
    1,
    1,
    1,
    1,
    1,
    135,
    466,
    439,
    341,
    106,
    109,
    107,
    105,
    106,
    106,
    105,
    105,
    105,
    108,
    193,
    46,
    52,
    4,
    4,
    2,
    44,
    104,
    48,
    5,
    8,
    5,
    7,
    42,
    72,
    48,
    43,
    43,
    49,
    43,
    42,
    46,
    45,
    45,
    44,
    65,
    1,
    1,
    30,
    2,
    44,
    2,
    1,
    12,
    57,
    2,
    1,
    6,
    2,
    1,
    9,
    1,
    5,
    2,
    3,
    1,
    6,
    8,
    6,
    10,
    33,
    30,
    9,
    9,
    1,
    344,
    3,
    1,
    6,
    2,
    14,
    5,
    7,
    2,
    8,
    3,
    79,
    43,
    7,
    26,
    14,
    5,
    8,
    14,
    6,
    22,
    4,
    61,
    18,
    323,
    11,
    11,
    34,
    10,
    16,
    24,
    10,
    14,
    10,
    13,
    11,
    13,
    13,
    8,
    305,
    9,
    25,
    12,
    20,
    546,
    21,
    18,
    15,
    19,
    11,
    23,
    16,
    20,
    18,
    33,
    23,
    40,
    506,
    10,
    15,
    13,
    521,
    10,
    18,
    16,
    20,
    10,
    14,
    18,
    10,
    38,
    42,
    35,
    9,
    234,
    254,
    236,
    212,
    224,
    218,
    227,
    62,
    205,
    360,
    226,
    237,
    235,
    228,
    227,
    53,
    210,
    228,
    209,
    214,
    321,
    218,
    257,
    225,
    227,
    239,
    202,
    236,
    212,
    250,
    206,
    465,
    251,
    294,
    356,
    331,
    325,
    290,
    310,
    289,
    309,
    398,
    488,
    546,
    640,
    429,
    427,
    493,
    1809,
    481,
    453,
    427,
    539,
    464,
    570,
    508,
    514,
    517,
    521,
    528,
    531,
    583,
    548,
    542,
    530,
    525,
    521,
    535,
    534,
    569,
    574,
    557,
    541,
    532,
    526,
    576,
    534,
    557,
    651,
    627,
    583,
    643,
    645,
    593,
    575,
    549,
    560,
    607,
    594,
    536,
    676,
    480,
    624,
    654,
    522,
    595,
    627,
    649,
    529,
    667,
    578,
    590,
    489,
    579,
    567,
    526,
    628,
    611,
    548,
    659,
    629,
    602,
    580,
    609,
    633,
    608,
    614,
    591,
    655,
    627,
    615,
    611,
    527,
    563,
    610,
    605,
    623,
    615,
    553,
    609,
    660,
    660,
    548,
    692,
    541,
    606,
    542,
    595,
    598,
    593,
    612,
    605,
    509,
    615,
    676,
    649,
    555,
    542,
    592,
    575,
    517,
    537,
    460,
    464,
    573,
    584,
    584,
    526,
    540,
    534,
    536,
    481,
    443,
    594,
    454,
    441,
    372,
    384,
    374,
    389,
    377,
    467,
    351,
    446,
    342,
    448,
    343,
    444,
    313,
    416,
    336,
    429,
    307,
    390,
    299,
    400,
    388,
    327,
    263,
    235];

// Keep these audio files in order so that the numbers of the episodes are
// always increasing.  Make sure you have the right file path as well
var a1 = { Number: 176, Filename: 'audio/beep.mp3' };
var a2 = { Number: 180, Filename: 'audio/beep.mp3' };

// Add all of the audio file objects to this array, in the same order
var audioFiles = [a1, a2];

var widthTracker = 15;

function makeBooks() {
  var fileIterator = 0;
  if (titles.length != height.length) {
    alert('Length of Title and Height Array is not the same!');
    alert('Title Array Length: ' + titles.length + ' Height Array Length: ' + height.length);
  } else {
    for (var i = 0; i < titles.length; i++) {
      var colorRand = Math.floor(Math.random() * colors.length);
      var del = Math.floor(Math.random() * (colors.length - 1)) + 1;
      var stripeRand = (colorRand + del) % colors.length;

      var width = Math.floor(Math.random() * (widthMax - widthMin)) + widthMin;

      var upperStripe = document.createElement('div');
      upperStripe.style.backgroundColor = '#DCBE87';
      upperStripe.style.backgroundColor = colors[stripeRand];
      upperStripe.classList.add('upper_stripe');

      var title = document.createElement('p');
      var t = '<b><center>Episode ' + (num + i) + ':</b><br>' + titles[i] + '</center>';
      title.innerHTML = t;

      var audio;
      var img;
      var audioFileExists = 0;
      if (fileIterator < audioFiles.length && audioFiles[fileIterator].Number == (num + i)) {
        audioFileExists = 1;
        audio = document.createElement('audio');
        audio.preload = 'auto';

        var sourceMpg = document.createElement('source');
        sourceMpg.src = audioFiles[fileIterator].Filename;
        sourceMpg.type = 'audio/mpeg';

        var sourceOgg = document.createElement('source');
        sourceOgg.src = audioFiles[fileIterator].Filename;
        sourceOgg.type = 'audio/ogg';

        audio.innerHTML = 'Your browser does not support this audio format.';
        audio.appendChild(sourceMpg);
        audio.appendChild(sourceOgg);

        img = document.createElement('img');
        img.src = 'speaker.png';
        fileIterator += 1;
      }

      var lowerStripe = document.createElement('div');
      lowerStripe.style.backgroundColor = '#DCBE87';
      lowerStripe.style.backgroundColor = colors[stripeRand];
      lowerStripe.classList.add('lower_stripe');

      // 250 + height =
      // 610 - h = marginT
      var ht = 200 + (height[i] / 2);
      var mt = 610 - ht;
      if (ht > 500) {
        width += (ht - 500);
        ht = 500;
        mt = 610 - ht;
      }

      var book = document.createElement('div');
      book.style.width = width + 'px';
      book.style.height = ht + 'px';
      book.style.marginTop = mt + 'px';
      book.style.backgroundColor = '#DCBE87';
      book.style.backgroundColor = colors[colorRand];
      book.classList.add('book');

      book.appendChild(upperStripe);
      book.appendChild(title);
      if (audioFileExists == 1) {
        book.appendChild(audio);
        book.appendChild(img);
      }

      book.appendChild(lowerStripe);

      widthTracker += 10 + width;

      document.getElementById('inner_wrapper').appendChild(book);

      $(function () {
        $('.book img').hover(
            function () {
                $(this).prev()[0].play();
              },

            function () {
                $(this).prev()[0].pause();
              }
        );
      });

    }

    var iw = document.getElementById('inner_wrapper');
    iw.style.width = widthTracker + 'px';
  }
}
